### PR TITLE
[rocon_app_manager_msgs] published interface types.

### PR DESCRIPTION
**Pull request by asmodehn**

### CODE REVIEW

**Comment by asmodehn** [comment]
Why not simply have each msg specification in the corresponding repository ?

**Comment by stonier** [comment]
The msg packages are the public api for ros. Like headers for libraries. Need to be able to generate them easily without having to compile the code.

1) Closed source packages. If the msg files are stuck in the same package as the source code, we can't give them directly to our collaborators unless we compile first and then find some way of packaging headers/libraries/modules/artifacts for them, for every esoteric platform they might be using. Easier just to point them at the message artifacts and tell them to build them themselves.

2) Minimise dependencies. You don't want to install and compile a long line of dependencies for the navigation stack (even assuming you can), just to get the message headers for `Goal.msg` so you can talk to somebody's navigation stack. This is usually an impossibility for cross-compilations.

3) Cross-languages. Similar to 2) We might not use java, and its unofficially supported, so we'd have no way of providing maven artifacts to a research lab so they can talk to our robots at a higher level. They certainly don't want to compile all of the internal robot software just so they can generate java artifacts themselves.

4) Potentially could put them in the same repo, but as a  different catkin package. However the build system isn't designed to handle compiling only certain packages in a repo, so it's become convention to have msg repos. This is a must anyway for closed source - separate closed source code repos and open source msg repos.

I think you probably get the gist of it...

**Comment by asmodehn** [comment]
Interesting, the software world used to have the same problem with C
headers...
Want to separate headers from source, hence the include/src folders
convention.
When compiling libraries the headers are copied along with binaries and
delivered to the costumer.

Ultimately the time of compiling the C code became not so much of a
problem. The headers compilation was the part taking big time ( exponential
complexity ), on everybody's machine.
Which is also one of the reason why modern languages got rid of headers as
a feature of the language. Even some C guys want to change it (clang has
modules as an improvement). But the concept of public/private is still
there in different locations.

Yet both are kept in same repos if possible, otherwise the cost of going
back revision in multiple places while making sure everything matches can
make the task so daunting that people don't really use revision anymore,
they just keep moving forward. And checking for bugs on different revision
is not really feasible anymore.

I actually understand the Ros situation as more a matter of "how we deliver
these specifications to the customer" : we dont give files directly,
instead we give urls to public repos ( is that a correct assumption ? )

So here is an idea for later : how about including the msg raw specs in api
docs ? We put them online somewhere (github pages, rosdocs). Then having
the ros tools be able to get these via url ( like wstool understanding wget
or curl to retrieve a bunch of them )

-> we can keep them in the same repo.
-> public interface made public when docs are ( and usually at same time as
the compiled version of the package is built )
-> we can deliver them easily to the customer via url/wstool

Now the world is moving to SDK/web services. But you can see the same
paradigm there... managing version between SDK and web services is a big
hurdle.
I think of ROS more in terms of SDK/services, since the interface
specification is about communication protocol.

Which means for me when i see "Node A has topic T1 T2 and service S1"
I can connect to T1 T2 and S1  and spend some time figuring out how they
work together.
But i would rather "import nodeA.SDK" and have it do the "public
interfacing" directly in python. Example : I am now writing a "watcher
thread for rapp_manager" that mirror the list of rapps as a python dict. We
could reuse in many places later : interactions_manager, rostful ( for
debugging only ), qt_app_manager, etc.

Then i would have a public repo with all SDK code ( and msg specs ), a
private repo with all service code ( and msg specs ) and msg specs exposed
in docs in case someone wants to debug our service or build a better sdk.
That may also remind you the "check version" first request i told you about
when explaining the flow of connection from webapp to rostful... you need
something like this at runtime to make sure versions are compatible before
you start doing anything.

-> Moving the msg specs in docs fit in a likely long term evolution of ROS.
-> Actually if we think about the msgs specs as the minimum necessary SDK,
what i find strange is that they re all in the same place, but pointing to
"services" in different repos. We will need to decide at some point how
many independent parts are in rocon.

And here is another ( complementary ) idea : how about including the msg
specs as a submodule in the matching service repo ? The link of repoA:vT
<-> repoB:vU will be kept in the repository history. Might be tricky to get
people to grasp it though...

--
AlexV

**Comment by stonier** [comment]
The C headers/libraries situation is quite different. The user actually needs both headers and libraries. i.e. they are tightly coupled.

In the ros world, the user needs only the messages, not the stack (e.g. navi stack) that runs on the robot. There is no coupling between the user and the navi stack. And if you were to introduce that, you introduce hundreds of robot specific dependencies (e.g. device drivers) to the user that he can't handle.

In addition, to whom does a message file belong? e.g. Laser.msg - there are at least a half a dozen laser drivers out there who all publish this message. It doesn't make sense to bind it to a particular driver. It also doesn't work to have a half a dozen different laser messages. That removes any device abstraction capability at the other side.

**Comment by stonier** [comment]
Some other FYI tidbits:

**Versioning**

Currently a convention that is applied for the core and industry standard packages are that aros distro (e.g. indigo) places a tight constraint on the release of messages (same goes for library ABI). The message format for a stable package should not change within that rosdistro version. This is the only way we have right now to ensure version matching between two systems. e.g. if they're both indigo, it should be guaranteed, if it's hydro and indigo - not going to work.

I can envisage times when this may not be possible though - e.g. a large bug forcing a necessary upgrade. At this point the only check is to require that everyone have the latest version, but this is not too dissimilar from the way something like chrome/google web services work. i.e. a google web service upgrades, breaks in chrome, which then asks you to upgrade to the latest chrome.

**Docs**

When we release message packages, they do currently build docs versioned against the rosdistro on the fly, e.g. http://docs.ros.org/indigo/api/yocs_msgs/html/index-msg.html.

**Comment by stonier** [comment]
I didn't follow exactly all of your notes above but I'd like to know in more detail how big web services/SDK's handle this problem better. Let's chat over coffee next week.

**Pull request merged**
